[package]
id = "s3yc2jedhhrrl2glypzwottdbqkj7kqy"
name = "AxFPS"
version = "0.2.0"
content = { type = "Playable", example = false }
ambient_version = "0.3.0"
authors = ["Gael Zarco"]
description= "An FPS game built through the Ambient engine tutorial."

[dependencies]
package_manager = { deployment = "4hEHArTmKMprisqnQPNxLK" }
base_assets = { deployment = "79plwEq1A0N3t0ExBOMTPM" }
character_controller = { deployment = "yV6nlkxj25cmkBhd4koe8" }
character_animation = { deployment = "4nLmHfcAlZkvWbK0NANMoC" }
hide_cursor = { deployment = "2ejmKJKgh6b4pTnwWPdv4s" }
performance_bar = { deployment = "Vd3QAwO2rrX55H9m2MeGl" }

[components]
bouncy_created = { type = "Duration" }

[message.Paint]
fields = { ray_origin = "Vec3", ray_dir = "Vec3" }
